// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
			/// <summary>
			/// Tag: musica
			/// 2D
			/// </summary>
			public const string musica = "musica";

			/// <summary>
			/// Tag: sfx
			/// 2D
			/// </summary>
			public const string sfx = "sfx";

		}

		public class Variables
		{
			/// <summary>
			/// Variable: bigvolume
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string bigvolume = "bigvolume";

			/// <summary>
			/// Variable: crushvar
			/// Range: [0 - 20]
			/// Type: Global
			/// </summary>
			public const string crushvar = "crushvar";

			/// <summary>
			/// Variable: littlevolume
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string littlevolume = "littlevolume";

			/// <summary>
			/// Variable: mediumvolume
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string mediumvolume = "mediumvolume";

			/// <summary>
			/// Variable: musicvar
			/// Range: [0 - 3]
			/// Type: Local
			/// </summary>
			public const string musicvar = "musicvar";

			/// <summary>
			/// Variable: sfxvar
			/// Range: [0 - 17]
			/// Type: Local
			/// </summary>
			public const string sfxvar = "sfxvar";

		}

		public class Channels
		{
			public const string Master = "Master";

			public const string sfx = "sfx";

		}
	}
}
